add_subdirectory(dagor_replay_test)
add_subdirectory(test_multiple_replays)
add_subdirectory(test_net_unpack)
add_subdirectory(create_entitiy)
add_subdirectory(test_init)
add_subdirectory(replay_profile)
add_subdirectory(dagor_replay_threading_test)
add_subdirectory(test_gstate_size)
add_subdirectory(testWrite)