// generated by replay parser codegen version 0.2
#pragma once

#include "mpi/reflection.h"
#include "mpi/serializers.h"
extern template class danet::ReflectionVar<uint32_t>;
extern template class danet::ReflectionVar<uint8_t>;
extern template class danet::ReflectionVar<std::vector<uint32_t>>;
extern template class danet::ReflectionVar<uint16_t>;
extern template class danet::ReflectionVar<ecs::EntityId>;
extern template class danet::ReflectionVar<danet::Crew>;
extern template class danet::ReflectionVar<std::vector<danet::Crew>>;
extern template class danet::ReflectionVar<bool>;
extern template class danet::ReflectionVar<danet::streak>;
extern template class danet::ReflectionVar<std::vector<danet::streak>>;
extern template class danet::ReflectionVar<int>;
extern template class danet::ReflectionVar<danet::zigZagPair>;
extern template class danet::ReflectionVar<std::vector<danet::zigZagPair>>;
extern template class danet::ReflectionVar<std::string>;
extern template class danet::ReflectionVar<char>;
extern template class danet::ReflectionVar<danet::WeatherEffect>;
extern template class danet::ReflectionVar<std::vector<danet::WeatherEffect>>;
extern template class danet::ReflectionVar<danet::UnitId>;
extern template class danet::ReflectionVar<uint64_t>;
extern template class danet::ReflectionVar<danet::Uid>;
extern template class danet::ReflectionVar<DataBlock>;
extern template class danet::ReflectionVar<danet::Country>;
extern template class danet::ReflectionVar<std::array<ecs::EntityId,20>>;
extern template class danet::ReflectionVar<danet::CrewUnitsList>;
extern template class danet::ReflectionVar<float>;
extern template class danet::ReflectionVar<std::vector<uint8_t>>;
extern template class danet::ReflectionVar<std::vector<uint16_t>>;
extern template class danet::ReflectionVar<danet::dummyForKillStreaksProgress>;
extern template class danet::ReflectionVar<danet::RoundScore>;
extern template class danet::ReflectionVar<danet::dummyForPlayerStat>;
extern template class danet::ReflectionVar<danet::dummyForFootballStat>;
extern template class danet::ReflectionVar<Point3>;
extern template class danet::ReflectionVar<danet::dummyForExitZonesSettings>;
extern template class danet::ReflectionVar<danet::WeatherEffects>;
extern template class danet::ReflectionVar<Point2>;
extern template class danet::ReflectionVar<danet::AreaFlagsEnum>;
extern template class danet::ReflectionVar<int8_t>;
extern template class danet::ReflectionVar<std::vector<danet::UnitId>>;
extern template class danet::ReflectionVar<danet::UnitIdStruct>;
extern template class danet::ReflectionVar<std::vector<danet::UnitIdStruct>>;
extern template class danet::ReflectionVar<std::array<std::string,2>>;
extern template class danet::ReflectionVar<danet::dummyForDeathInfo>;
extern template class danet::ReflectionVar<danet::KillerStruct>;
extern template class danet::ReflectionVar<danet::DamagedState>;
extern template class danet::ReflectionVar<std::vector<danet::DamagedState>>;
extern template class danet::ReflectionVar<danet::WeaponsMask>;
