// generated by replay parser codegen version 0.1
#pragma once
#include "mpi/serializers.h"
#include "mpi/codegen/ReflectableObjects/BombingZone.h"
#include "mpi/codegen/ReflectableObjects/CaptureZone.h"
#include "mpi/codegen/ReflectableObjects/ExitZone.h"
#include "mpi/codegen/ReflectableObjects/GeneralState.h"
#include "mpi/codegen/ReflectableObjects/GlobalElo.h"
#include "mpi/codegen/ReflectableObjects/MPlayer.h"
#include "mpi/codegen/ReflectableObjects/PickupZone.h"
#include "mpi/codegen/ReflectableObjects/RearmZone.h"
#include "mpi/codegen/ReflectableObjects/TeamData.h"
#include "mpi/Replication.h"
