// generated by replay parser codegen version 0.1
#pragma once
#define REPL_VER(x) \
  if (!(x))         \
    return false

namespace danet {
  int uint32_tCoder(DANET_ENCODER_SIGNATURE);

  int uint8_tCoder(DANET_ENCODER_SIGNATURE);

  int uint32_t_uint8_tvectorCoder(DANET_ENCODER_SIGNATURE);

  int uint16_tCoder(DANET_ENCODER_SIGNATURE);

  int boolCoder(DANET_ENCODER_SIGNATURE);

  int floatCoder(DANET_ENCODER_SIGNATURE);

  int stringCoder(DANET_ENCODER_SIGNATURE);

  int danetUnitId_uint8_tvectorCoder(DANET_ENCODER_SIGNATURE);

  int danetUnitIdStruct_uint8_tvectorCoder(DANET_ENCODER_SIGNATURE);

  int uint8_t_uint8_tvectorCoder(DANET_ENCODER_SIGNATURE);

  int dummyForExitZonesSettingsCoder(DANET_ENCODER_SIGNATURE);

  int intCoder(DANET_ENCODER_SIGNATURE);

  int WeatherEffectsCoder(DANET_ENCODER_SIGNATURE);

  int DataBlockCoder(DANET_ENCODER_SIGNATURE);

  int teamAvgEloRatingsCoder(DANET_ENCODER_SIGNATURE);

  int UidCoder(DANET_ENCODER_SIGNATURE);

  int EntityIdCoder(DANET_ENCODER_SIGNATURE);

  int ecsEntityId_20arrayCoder(DANET_ENCODER_SIGNATURE);

  int CrewUnitsListCoder(DANET_ENCODER_SIGNATURE);

  int uint16_t_uint8_tvectorCoder(DANET_ENCODER_SIGNATURE);

  int dummyForKillStreaksProgressCoder(DANET_ENCODER_SIGNATURE);

  int RoundScoreCoder(DANET_ENCODER_SIGNATURE);

  int dummyForPlayerStatCoder(DANET_ENCODER_SIGNATURE);

  int dummyForFootballStatCoder(DANET_ENCODER_SIGNATURE);


  template <>
  struct DefaultEncoderChooser<uint8_t> {
    static constexpr reflection_var_encoder coder = uint8_tCoder;
  };

  template <>
  struct DefaultEncoderChooser<uint16_t> {
    static constexpr reflection_var_encoder coder = uint16_tCoder;
  };

  template <>
  struct DefaultEncoderChooser<float> {
    static constexpr reflection_var_encoder coder = floatCoder;
  };

  template <>
  struct DefaultEncoderChooser<std::vector<danet::UnitId>> {
    static constexpr reflection_var_encoder coder = danetUnitId_uint8_tvectorCoder;
  };

  template <>
  struct DefaultEncoderChooser<std::vector<danet::UnitIdStruct>> {
    static constexpr reflection_var_encoder coder = danetUnitIdStruct_uint8_tvectorCoder;
  };

  template <>
  struct DefaultEncoderChooser<std::vector<uint8_t>> {
    static constexpr reflection_var_encoder coder = uint8_t_uint8_tvectorCoder;
  };

  template <>
  struct DefaultEncoderChooser<danet::dummyForExitZonesSettings> {
    static constexpr reflection_var_encoder coder = dummyForExitZonesSettingsCoder;
  };

  template <>
  struct DefaultEncoderChooser<int> {
    static constexpr reflection_var_encoder coder = intCoder;
  };

  template <>
  struct DefaultEncoderChooser<bool> {
    static constexpr reflection_var_encoder coder = boolCoder;
  };

  template <>
  struct DefaultEncoderChooser<danet::WeatherEffects> {
    static constexpr reflection_var_encoder coder = WeatherEffectsCoder;
  };

  template <>
  struct DefaultEncoderChooser<DataBlock> {
    static constexpr reflection_var_encoder coder = DataBlockCoder;
  };

  template <>
  struct DefaultEncoderChooser<danet::teamAvgEloRatings> {
    static constexpr reflection_var_encoder coder = teamAvgEloRatingsCoder;
  };

  template <>
  struct DefaultEncoderChooser<danet::Uid> {
    static constexpr reflection_var_encoder coder = UidCoder;
  };

  template <>
  struct DefaultEncoderChooser<std::string> {
    static constexpr reflection_var_encoder coder = stringCoder;
  };

  template <>
  struct DefaultEncoderChooser<uint32_t> {
    static constexpr reflection_var_encoder coder = uint32_tCoder;
  };

  template <>
  struct DefaultEncoderChooser<std::array<ecs::EntityId,20>> {
    static constexpr reflection_var_encoder coder = ecsEntityId_20arrayCoder;
  };

  template <>
  struct DefaultEncoderChooser<danet::CrewUnitsList> {
    static constexpr reflection_var_encoder coder = CrewUnitsListCoder;
  };

  template <>
  struct DefaultEncoderChooser<ecs::EntityId> {
    static constexpr reflection_var_encoder coder = EntityIdCoder;
  };

  template <>
  struct DefaultEncoderChooser<std::vector<uint32_t>> {
    static constexpr reflection_var_encoder coder = uint32_t_uint8_tvectorCoder;
  };

  template <>
  struct DefaultEncoderChooser<std::vector<uint16_t>> {
    static constexpr reflection_var_encoder coder = uint16_t_uint8_tvectorCoder;
  };

  template <>
  struct DefaultEncoderChooser<danet::dummyForKillStreaksProgress> {
    static constexpr reflection_var_encoder coder = dummyForKillStreaksProgressCoder;
  };

  template <>
  struct DefaultEncoderChooser<danet::RoundScore> {
    static constexpr reflection_var_encoder coder = RoundScoreCoder;
  };

  template <>
  struct DefaultEncoderChooser<danet::dummyForPlayerStat> {
    static constexpr reflection_var_encoder coder = dummyForPlayerStatCoder;
  };

  template <>
  struct DefaultEncoderChooser<danet::dummyForFootballStat> {
    static constexpr reflection_var_encoder coder = dummyForFootballStatCoder;
  };
}