// generated by replay parser codegen version 0.1
#pragma once
namespace danet {
  struct RoundScore {
    uint32_t combined{};
    std::vector<uint32_t> scores{};
  };
  struct dummyForFootballStat {
    uint16_t v1{};
    uint16_t v2{};
    uint16_t v3{};
  };
  struct Crew {
    ecs::entity_id_t e1{};
    ecs::entity_id_t e2{};
    uint8_t v1{};
    uint8_t v2{};
  };
  struct CrewUnitsList {
    std::vector<danet::Crew> crew{};
  };
  struct dummyForPlayerStat {
    uint16_t v1{};
    uint16_t v2{};
    uint16_t v3{};
    uint16_t v4{};
    uint16_t v5{};
    uint16_t v6{};
    uint16_t v7{};
    uint16_t v8{};
    uint16_t v9{};
    uint16_t v10{};
    uint16_t v11{};
    uint16_t v12{};
    uint32_t v13{};
    uint32_t v14{};
    uint16_t v15{};
    uint16_t v16{};
    uint16_t v17{};
    uint16_t v18{};
    uint32_t v19{};
    uint16_t v20{};
    uint16_t v21{};
    uint16_t v22{};
    uint16_t v23{};
    uint16_t v24{};
  };
  struct streak {
    uint8_t v1{};
    bool v2{};
    bool v3{};
  };
  struct dummyForKillStreaksProgress {
    std::vector<danet::streak> vals{};
  };
  struct teamAvgEloRatings {
    float team1{};
    float team2{};
    float team3{};
  };
  struct zigZagPair {
    danet::zigZagInt v1{};
    danet::zigZagInt v2{};
  };
  struct dummyForExitZonesSettings {
    danet::zigZagVector<danet::zigZagPair> vals{};
  };
  struct WeatherEffect {
    std::string name{};
    char effect_data[48]{};
  };
  struct WeatherEffects {
    std::vector<danet::WeatherEffect> effects{};
  };
  struct UnitIdStruct {
    danet::UnitId uid{};
    uint8_t thang{};
  };
}
