// generated by replay parser codegen version 0.2
#pragma once
#include <boost/describe.hpp>
namespace danet {
  struct RoundScore {
    uint32_t combined{};
    std::vector<uint32_t> scores{};
    bool operator==(const RoundScore& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(RoundScore, (), (combined, scores))
  struct dummyForFootballStat {
    uint16_t v1{};
    uint16_t v2{};
    uint16_t v3{};
    bool operator==(const dummyForFootballStat& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(dummyForFootballStat, (), (v1, v2, v3))
  struct Crew {
    ecs::EntityId e1{};
    ecs::EntityId e2{};
    uint8_t v1{};
    uint8_t v2{};
    bool operator==(const Crew& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(Crew, (), (e1, e2, v1, v2))
  struct CrewUnitsList {
    std::vector<danet::Crew> crew{};
    bool operator==(const CrewUnitsList& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(CrewUnitsList, (), (crew))
  struct dummyForPlayerStat {
    uint16_t v1{};
    uint16_t v2{};
    uint16_t v3{};
    uint16_t v4{};
    uint16_t v5{};
    uint16_t v6{};
    uint16_t v7{};
    uint16_t v8{};
    uint16_t v9{};
    uint16_t v10{};
    uint16_t v11{};
    uint16_t v12{};
    uint32_t v13{};
    uint32_t v14{};
    uint16_t v15{};
    uint16_t v16{};
    uint16_t v17{};
    uint16_t v18{};
    uint32_t v19{};
    uint16_t v20{};
    uint16_t v21{};
    uint16_t v22{};
    uint16_t v23{};
    uint16_t v24{};
    bool operator==(const dummyForPlayerStat& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(dummyForPlayerStat, (), (v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24))
  struct streak {
    uint8_t v1{};
    bool v2{};
    bool v3{};
    bool operator==(const streak& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(streak, (), (v1, v2, v3))
  struct dummyForKillStreaksProgress {
    std::vector<danet::streak> vals{};
    bool operator==(const dummyForKillStreaksProgress& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(dummyForKillStreaksProgress, (), (vals))
  struct zigZagPair {
    int v1{};
    int v2{};
    bool operator==(const zigZagPair& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(zigZagPair, (), (v1, v2))
  struct dummyForExitZonesSettings {
    std::vector<danet::zigZagPair> vals{};
    bool operator==(const dummyForExitZonesSettings& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(dummyForExitZonesSettings, (), (vals))
  struct WeatherEffect {
    std::string name{};
    char effect_data[48]{};
    bool operator==(const WeatherEffect& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(WeatherEffect, (), (name, effect_data))
  struct WeatherEffects {
    std::vector<danet::WeatherEffect> effects{};
    bool operator==(const WeatherEffects& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(WeatherEffects, (), (effects))
  struct UnitIdStruct {
    danet::UnitId uid{};
    uint8_t thang{};
    bool operator==(const UnitIdStruct& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(UnitIdStruct, (), (uid, thang))
  struct dummyForDeathInfo {
    uint8_t v1{};
    uint8_t v2{};
    uint16_t v3{};
    bool v4{};
    bool v5{};
    bool operator==(const dummyForDeathInfo& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(dummyForDeathInfo, (), (v1, v2, v3, v4, v5))
  struct KillerStruct {
    uint64_t player_id{};
    uint16_t uid{};
    std::string vehicle{};
    bool operator==(const KillerStruct& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(KillerStruct, (), (player_id, uid, vehicle))
  struct DamagedState {
    uint16_t v1{};
    uint8_t v2{};
    bool operator==(const DamagedState& other) const = default;
  };
BOOST_DESCRIBE_STRUCT(DamagedState, (), (v1, v2))
}
