// generated by replay parser codegen version 0.2
#include "mpi/serializers.h"
#include "mpi/codegen/ReflIncludes.h"
void danet::ReflectableObject::drawObject() const {}
void MPlayer::drawObject() const {}
void TeamData::drawObject() const {}
void GlobalElo::drawObject() const {}
void GeneralState::drawObject() const {}
void MissionArea::drawObject() const {}
void MissionZone::drawObject() const {}
void BombingZone::drawObject() const {}
void CaptureZone::drawObject() const {}
void RearmZone::drawObject() const {}
void ExitZone::drawObject() const {}
void PickupZone::drawObject() const {}
void BaseExtReflectable::drawObject() const {}
void FMWReflectable::drawObject() const {}
void GMReflectable::drawObject() const {}
void DVMReflectable::drawObject() const {}
void FM_DVMReflectable::drawObject() const {}
void GM_DVMReflectable::drawObject() const {}
void UnitWeaponsMask::drawObject() const {}
