// generated by replay parser codegen version 0.2
#pragma once

class BaseExtReflectable : public danet::ReflectableObject {
public:
  DECL_REFLECTION(BaseExtReflectable, danet::ReflectableObject)
  danet::ReflectionVar<bool> isAlternativeShotFreq{"isAlternativeShotFreq", &brokenTurretDriveSpeed, 33};
  danet::ReflectionVar<float> brokenTurretDriveSpeed{"brokenTurretDriveSpeed", &brokenTurretDriveMult, 55};
  danet::ReflectionVar<float> brokenTurretDriveMult{"brokenTurretDriveMult", &isBreechDamaged, 56};
  danet::ReflectionVar<bool> isBreechDamaged{"isBreechDamaged", &hasModuleEffectsToRepair, 57};
  danet::ReflectionVar<bool> hasModuleEffectsToRepair{"hasModuleEffectsToRepair", &moduleEffectsRepairAtTime, 58};
  danet::ReflectionVar<float> moduleEffectsRepairAtTime{"moduleEffectsRepairAtTime", &curNightVisionMode, 59};
  danet::ReflectionVar<int> curNightVisionMode{"curNightVisionMode", &dummyVarForMissionAddText, 40};
  danet::ReflectionVar<std::array<std::string, 2>> dummyVarForMissionAddText{"dummyVarForMissionAddText",
                                                                             &supportPlanesCount, 5};
  danet::ReflectionVar<uint32_t> supportPlanesCount{"supportPlanesCount", &supportPlaneCatapultsFuseMask, 49};
  danet::ReflectionVar<uint8_t> supportPlaneCatapultsFuseMask{"supportPlaneCatapultsFuseMask", &lastBuildingTime, 50};
  danet::ReflectionVar<float> lastBuildingTime{"lastBuildingTime", &visualReloadProgress, 62};
  danet::ReflectionVar<uint8_t> visualReloadProgress{"visualReloadProgress", &briefMalfunctionState, 6};
  danet::ReflectionVar<uint16_t> briefMalfunctionState{"briefMalfunctionState", &bombDelayExplosion, 7};
  danet::ReflectionVar<float> bombDelayExplosion{"bombDelayExplosion", &delayWithFlightTime, 8};
  danet::ReflectionVar<bool> delayWithFlightTime{"delayWithFlightTime", &rocketFuseDist, 9};
  danet::ReflectionVar<float> rocketFuseDist{"rocketFuseDist", &torpedoDiveDepth, 10};
  danet::ReflectionVar<float> torpedoDiveDepth{"torpedoDiveDepth", &dummyForDeathInfo, 44};
  danet::ReflectionVar<danet::dummyForDeathInfo> dummyForDeathInfo{"dummyForDeathInfo", &lastContactTime, 11};
  danet::ReflectionVar<float> lastContactTime{"lastContactTime", &lastContactTimeRel, 31};
  danet::ReflectionVar<float> lastContactTimeRel{"lastContactTimeRel", &allowBailout, 14};
  danet::ReflectionVar<bool> allowBailout{"allowBailout", &repairAssistee, 43};
  danet::ReflectionVar<uint16_t> repairAssistee{"repairAssistee", &repairAssistant, 15};
  danet::ReflectionVar<uint16_t> repairAssistant{"repairAssistant", &extinguishAssistee, 16};
  danet::ReflectionVar<uint16_t> extinguishAssistee{"extinguishAssistee", &extinguishAssistant, 45};
  danet::ReflectionVar<uint16_t> extinguishAssistant{"extinguishAssistant", &invulnerable, 46};
  danet::ReflectionVar<bool> invulnerable{"invulnerable", &enableGunners, 17};
  danet::ReflectionVar<uint8_t> enableGunners{"enableGunners", &enableCiwsGunners, 18};
  danet::ReflectionVar<uint8_t> enableCiwsGunners{"enableCiwsGunners", &vulnerableByUnitUId, 64};
  danet::ReflectionVar<uint32_t> vulnerableByUnitUId{"vulnerableByUnitUId", &dummyForUnitFlags, 19};
  danet::ReflectionVar<uint32_t> dummyForUnitFlags{"dummyForUnitFlags", &lowRateUnitFlags, 20};
  danet::ReflectionVar<uint32_t> lowRateUnitFlags{"lowRateUnitFlags", &unitState, 21};
  danet::ReflectionVar<uint16_t> unitState{"unitState", &farthestExitZoneId, 22};
  danet::ReflectionVar<uint32_t> farthestExitZoneId{"farthestExitZoneId", &unitArmyNo, 60};
  danet::ReflectionVar<uint8_t> unitArmyNo{"unitArmyNo", &stealthRadiusSq, 23};
  danet::ReflectionVar<float> stealthRadiusSq{"stealthRadiusSq", &stealthArmyMask, 24};
  danet::ReflectionVar<uint8_t> stealthArmyMask{"stealthArmyMask", &fpvRocketCameraControlEnabled, 25};
  danet::ReflectionVar<bool> fpvRocketCameraControlEnabled{"fpvRocketCameraControlEnabled", &scoutStartTime, 39};
  danet::ReflectionVar<float> scoutStartTime{"scoutStartTime", &scoutCooldown, 26};
  danet::ReflectionVar<float> scoutCooldown{"scoutCooldown", &prepareRepairAssisteeTime, 27};
  danet::ReflectionVar<float> prepareRepairAssisteeTime{"prepareRepairAssisteeTime", &prepareRepairAssistantTime, 28};
  danet::ReflectionVar<float> prepareRepairAssistantTime{"prepareRepairAssistantTime", &prepareExtinguishAssistantTime,
                                                         35};
  danet::ReflectionVar<float> prepareExtinguishAssistantTime{"prepareExtinguishAssistantTime", &nextUseArtilleryTime,
                                                             47};
  danet::ReflectionVar<float> nextUseArtilleryTime{"nextUseArtilleryTime", &prepareRepairCooldownsTime, 29};
  danet::ReflectionVar<float> prepareRepairCooldownsTime{"prepareRepairCooldownsTime", &killer, 37};
  danet::ReflectionVar<danet::KillerStruct> killer{"killer", &isNeedRepairHelp, 30};
  danet::ReflectionVar<bool> isNeedRepairHelp{"isNeedRepairHelp", &isNeedExtinguishHelp, 34};
  danet::ReflectionVar<bool> isNeedExtinguishHelp{"isNeedExtinguishHelp", &repairCooldowns, 48};
  danet::ReflectionVar<bool> repairCooldowns{"repairCooldowns", &maskingFactor, 38};
  danet::ReflectionVar<float> maskingFactor{"maskingFactor", &fuseModeIndex, 32};
  danet::ReflectionVar<uint32_t> fuseModeIndex{"fuseModeIndex", &timeToNextSmokeScreen, 61};
  danet::ReflectionVar<float> timeToNextSmokeScreen{"timeToNextSmokeScreen", &smokeScreenCount, 51};
  danet::ReflectionVar<uint8_t> smokeScreenCount{"smokeScreenCount", &smokeScreenActived, 52};
  danet::ReflectionVar<bool> smokeScreenActived{"smokeScreenActived", &crewStatMult, 53};
  danet::ReflectionVar<float> crewStatMult{"crewStatMult", nullptr, 63};

  BaseExtReflectable() : ReflectableObject() {
    varList.head = &isAlternativeShotFreq;
    varList.tail = &crewStatMult;
  }
};

ECS_DECLARE_CREATABLE_TYPE(BaseExtReflectable);
