// generated by replay parser codegen version 0.2
#pragma once

class BombingZone : public MissionZone {
public:
  DECL_REPLICATION(BombingZone, MissionZone)
  void drawObject() const override;
  danet::ReflectionVar<float> curZoneIntegrity{"curZoneIntegrity", nullptr, 67};
  explicit BombingZone(mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : MissionZone(oid)  {
    flags.next = &curZoneIntegrity;
    varList.tail = &curZoneIntegrity;
  }
  friend ParserState;
};

