// generated by replay parser codegen version 0.2
#pragma once

class BombingZone : public BaseZone {
public:
  DECL_REPLICATION(BombingZone, BaseZone)
  danet::ReflectionVar<float> curZoneIntegrity{"curZoneIntegrity", nullptr, 67};
  BombingZone() : BaseZone()  {
    flags.next = &curZoneIntegrity;
    varList.tail = &curZoneIntegrity;
  }
};

