// generated by replay parser codegen version 0.1
#pragma once

class BombingZone : public danet::ReplicatedObject {
public:
  DECL_REFLECTION(BombingZone, danet::ReplicatedObject)

  static int you_forget_to_put_IMPLEMENT_REPLICATION_4_BombingZone;

  int getClassId() const override {
    G_STATIC_ASSERT(danet::IsBase<danet::ReplicatedObject DANET_COMMA ThisClass>::Value);
    return you_forget_to_put_IMPLEMENT_REPLICATION_4_BombingZone;
  }

  void serializeReplicaCreationData(BitStream &bs) const override;

  static danet::ReplicatedObject *createReplicatedObject(BitStream &bs, ParserState *state);

  danet::ReflectionVar<uint8_t> armyNo{"armyNo", &flags, 2};
  danet::ReflectionVar<uint16_t> flags{"flags", &curZoneIntegrity, 3};
  danet::ReflectionVar<float> curZoneIntegrity{"curZoneIntegrity", nullptr, 67};

  BombingZone() : ReplicatedObject() {
    varList.head = &armyNo;
    varList.tail = &curZoneIntegrity;
  }
};

