// generated by replay parser codegen version 0.1
#pragma once

class CaptureZone : public danet::ReplicatedObject {
public:
  DECL_REPLICATION(CaptureZone, danet::ReplicatedObject)
  danet::ReflectionVar<uint8_t> armyNo{"armyNo", &flags, 2};
  danet::ReflectionVar<uint16_t> flags{"flags", &mpTimeX100, 3};
  danet::ReflectionVar<uint8_t> mpTimeX100{"mpTimeX100", &conqTeam, 67};
  danet::ReflectionVar<uint8_t> conqTeam{"conqTeam", &iconIdx, 68};
  danet::ReflectionVar<uint8_t> iconIdx{"iconIdx", &dummyVarForCapturers, 69};
  danet::ReflectionVar<std::vector<danet::UnitId>> dummyVarForCapturers{"dummyVarForCapturers", &dummyVarForCapturePart, 70};
  danet::ReflectionVar<std::vector<danet::UnitIdStruct>> dummyVarForCapturePart{"dummyVarForCapturePart", &dummyVarForNumOfActiveCapturers, 71};
  danet::ReflectionVar<std::vector<uint8_t>> dummyVarForNumOfActiveCapturers{"dummyVarForNumOfActiveCapturers", nullptr, 72};
  CaptureZone() : ReplicatedObject()  {
    varList.head = &armyNo;
    varList.tail = &dummyVarForNumOfActiveCapturers;
  }
};

