// generated by replay parser codegen version 0.2
#pragma once

class CaptureZone : public BaseZone {
public:
  DECL_REPLICATION(CaptureZone, BaseZone)
  danet::ReflectionVar<uint8_t> mpTimeX100{"mpTimeX100", &conqTeam, 67};
  danet::ReflectionVar<uint8_t> conqTeam{"conqTeam", &iconIdx, 68};
  danet::ReflectionVar<uint8_t> iconIdx{"iconIdx", &dummyVarForCapturers, 69};
  danet::ReflectionVar<std::vector<danet::UnitId>> dummyVarForCapturers{"dummyVarForCapturers", &dummyVarForCapturePart, 70};
  danet::ReflectionVar<std::vector<danet::UnitIdStruct>> dummyVarForCapturePart{"dummyVarForCapturePart", &dummyVarForNumOfActiveCapturers, 71};
  danet::ReflectionVar<std::vector<uint8_t>> dummyVarForNumOfActiveCapturers{"dummyVarForNumOfActiveCapturers", nullptr, 72};
  CaptureZone() : BaseZone()  {
    flags.next = &mpTimeX100;
    varList.tail = &dummyVarForNumOfActiveCapturers;
  }
};

