// generated by replay parser codegen version 0.2
#pragma once

class CUDReflectable : public danet::ReflectableObject {
public:
  DECL_REFLECTION(CUDReflectable, danet::ReflectableObject)

  CUDReflectable() : ReflectableObject() { varList.head = &; }
};

ECS_DECLARE_CREATABLE_TYPE(CUDReflectable);
