// generated by replay parser codegen version 0.2
#pragma once

class DVMReflectable : public danet::ReflectableObject {
public:
  DECL_REFLECTION(DVMReflectable, danet::ReflectableObject)
  danet::ReflectionVar<std::vector<danet::DamagedState>> dummyVarForDamagedStateReflection{
    "dummyVarForDamagedStateReflection", nullptr, 3, danet::dummyVarForDamagedStateReflectionCoder};
  DVMReflectable() : ReflectableObject() {
    varList.head = &dummyVarForDamagedStateReflection;
    varList.tail = &dummyVarForDamagedStateReflection;
  }
};

ECS_DECLARE_CREATABLE_TYPE(DVMReflectable);
