// generated by replay parser codegen version 0.2
#pragma once

class DVMReflectable : public danet::ReflectableObject {
public:
  DECL_REFLECTION(DVMReflectable, danet::ReflectableObject)
  void drawObject() const override;
  danet::ReflectionVar<std::vector<danet::DamagedState>> dummyVarForDamagedStateReflection{"dummyVarForDamagedStateReflection", nullptr, 3, danet::dummyVarForDamagedStateReflectionCoder};
  explicit DVMReflectable(ParserState *state, mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : ReflectableObject(state, oid)  {
    varList.head = &dummyVarForDamagedStateReflection;
    varList.tail = &dummyVarForDamagedStateReflection;
  }
  friend ParserState;
};

