// generated by replay parser codegen version 0.1
#pragma once

class ExitZone : public danet::ReplicatedObject {
public:
  DECL_REPLICATION(ExitZone, danet::ReplicatedObject)
  danet::ReflectionVar<uint8_t> armyNo{"armyNo", &flags, 2};
  danet::ReflectionVar<uint16_t> flags{"flags", nullptr, 3};
  ExitZone() : ReplicatedObject()  {
    varList.head = &armyNo;
    varList.tail = &flags;
  }
};

