// generated by replay parser codegen version 0.2
#pragma once

class ExitZone : public MissionZone {
public:
  DECL_REPLICATION(ExitZone, MissionZone)
  void drawObject() const override;
  explicit ExitZone(ParserState *state, mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : MissionZone(state, oid)  {
  }
  friend ParserState;
};

