// generated by replay parser codegen version 0.2
#pragma once

class FM_DVMReflectable : public DVMReflectable {
public:
  DECL_REFLECTION(FM_DVMReflectable, DVMReflectable)

  FM_DVMReflectable() : DVMReflectable() {}
};

ECS_DECLARE_CREATABLE_TYPE(FM_DVMReflectable);
