// generated by replay parser codegen version 0.2
#pragma once

class FM_FXReflectable : public danet::ReflectableObject {
public:
  DECL_REFLECTION(FM_FXReflectable, danet::ReflectableObject)

  FM_FXReflectable() : ReflectableObject() { varList.head = &; }
};

ECS_DECLARE_CREATABLE_TYPE(FM_FXReflectable);
