// generated by replay parser codegen version 0.2
#pragma once

class FMWReflectable : public BaseExtReflectable {
public:
  DECL_REFLECTION(FMWReflectable, BaseExtReflectable)

  FMWReflectable() : BaseExtReflectable() {}
};

ECS_DECLARE_CREATABLE_TYPE(FMWReflectable);
