// generated by replay parser codegen version 0.2
#pragma once

class FMWReflectable : public BaseExtReflectable {
public:
  DECL_REFLECTION(FMWReflectable, BaseExtReflectable)
  void drawObject() const override;
  explicit FMWReflectable(mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : BaseExtReflectable(oid)  {
  }
  friend ParserState;
};

ECS_DECLARE_CREATABLE_TYPE(FMWReflectable);
