// generated by replay parser codegen version 0.2
#pragma once

class GlobalElo : public danet::ReflectableObject {
public:
  DECL_REFLECTION(GlobalElo, danet::ReflectableObject)
  void drawObject() const override;
  danet::ReflectionVar<Point3> teamAvgEloRatings{"teamAvgEloRatings", nullptr, 2};
  explicit GlobalElo(mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : ReflectableObject(oid)  {
    varList.head = &teamAvgEloRatings;
    varList.tail = &teamAvgEloRatings;
  }
  friend ParserState;
};

ECS_DECLARE_CREATABLE_TYPE(GlobalElo);
