// generated by replay parser codegen version 0.1
#pragma once

class GlobalElo : public danet::ReflectableObject {
public:
  DECL_REFLECTION(GlobalElo, danet::ReflectableObject)
  danet::ReflectionVar<danet::teamAvgEloRatings> teamAvgEloRatings{"teamAvgEloRatings", nullptr, 2};
  GlobalElo() : ReflectableObject()  {
    varList.head = &teamAvgEloRatings;
    varList.tail = &teamAvgEloRatings;
  }
};

ECS_DECLARE_CREATABLE_TYPE(GlobalElo);
