// generated by replay parser codegen version 0.2
#pragma once

class GM_DVMReflectable : public DVMReflectable {
public:
  DECL_REFLECTION(GM_DVMReflectable, DVMReflectable)

  GM_DVMReflectable() : DVMReflectable() {}
};

ECS_DECLARE_CREATABLE_TYPE(GM_DVMReflectable);
