// generated by replay parser codegen version 0.2
#pragma once

class GM_DVMReflectable : public DVMReflectable {
public:
  DECL_REFLECTION(GM_DVMReflectable, DVMReflectable)
  void drawObject() const override;
  explicit GM_DVMReflectable(ParserState *state, mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : DVMReflectable(state, oid)  {
  }
  friend ParserState;
};

