// generated by replay parser codegen version 0.2
#pragma once

class GMReflectable : public BaseExtReflectable {
public:
  DECL_REFLECTION(GMReflectable, BaseExtReflectable)

  GMReflectable() : BaseExtReflectable() {}
};

ECS_DECLARE_CREATABLE_TYPE(GMReflectable);
