// generated by replay parser codegen version 0.2
#pragma once

class INFReflectable : public danet::ReflectableObject {
public:
  DECL_REFLECTION(INFReflectable, danet::ReflectableObject)

  INFReflectable() : ReflectableObject() { varList.head = &; }
};

ECS_DECLARE_CREATABLE_TYPE(INFReflectable);
