// generated by replay parser codegen version 0.2
#pragma once

class MissionZone : public danet::ReplicatedObject {
public:
  MissionArea* area{};
public:
  DECL_REPLICATION(MissionZone, danet::ReplicatedObject)
  void drawObject() const override;
  danet::ReflectionVar<uint8_t> armyNo{"armyNo", &flags, 2};
  danet::ReflectionVar<uint16_t> flags{"flags", nullptr, 3};
  explicit MissionZone(ParserState *state, mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : ReplicatedObject(state, oid)  {
    varList.head = &armyNo;
    varList.tail = &flags;
  }
  friend ParserState;
};

