// generated by replay parser codegen version 0.2
#pragma once

class MissionArea : public danet::ReplicatedObject {
public:
  DECL_REPLICATION(MissionArea, danet::ReplicatedObject)
  void drawObject() const override;
  TMatrix tm{};
  danet::ReflectionVar<danet::AreaFlagsEnum> areaFlags{"areaFlags", nullptr, 2};
  explicit MissionArea(mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : ReplicatedObject(oid)  {
    varList.head = &areaFlags;
    varList.tail = &areaFlags;
  }
  friend ParserState;
};

