// generated by replay parser codegen version 0.2
#pragma once

class PickupZone : public BaseZone {
public:
  DECL_REPLICATION(PickupZone, BaseZone)
  danet::ReflectionVar<bool> showOnTacticalMap{"showOnTacticalMap", nullptr, 67};
  PickupZone() : BaseZone()  {
    flags.next = &showOnTacticalMap;
    varList.tail = &showOnTacticalMap;
  }
};

