// generated by replay parser codegen version 0.2
#pragma once

class PickupZone : public MissionZone {
public:
  DECL_REPLICATION(PickupZone, MissionZone)
  void drawObject() const override;
  danet::ReflectionVar<bool> showOnTacticalMap{"showOnTacticalMap", nullptr, 67};
  explicit PickupZone(mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : MissionZone(oid)  {
    flags.next = &showOnTacticalMap;
    varList.tail = &showOnTacticalMap;
  }
  friend ParserState;
};

