// generated by replay parser codegen version 0.2
#pragma once

class RearmZone : public MissionZone {
public:
  DECL_REPLICATION(RearmZone, MissionZone)
  void drawObject() const override;
  explicit RearmZone(ParserState *state, mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : MissionZone(state, oid)  {
  }
  friend ParserState;
};

