// generated by replay parser codegen version 0.1
#pragma once

class TeamData : public danet::ReflectableObject {
public:
  danet::ReflectionVar<uint16_t> score{"score", &tickets, 2};
  danet::ReflectionVar<uint16_t> tickets{"tickets", &orderCooldownTotal, 3};
  danet::ReflectionVar<uint32_t> orderCooldownTotal{"orderCooldownTotal", &orderCooldownLeft, 4};
  danet::ReflectionVar<uint32_t> orderCooldownLeft{"orderCooldownLeft", &spawnScore, 5};
  danet::ReflectionVar<uint32_t> spawnScore{"spawnScore", &roundScore, 6};
  danet::ReflectionVar<uint32_t> roundScore{"roundScore", nullptr, 7};
  TeamData() {
    varList.head = &score;
    varList.tail = &roundScore;
  }
};

ECS_DECLARE_CREATABLE_TYPE(TeamData);
