// generated by replay parser codegen version 0.2
#pragma once

class TeamData : public danet::ReflectableObject {
public:
  DECL_REFLECTION(TeamData, danet::ReflectableObject)
  void drawObject() const override;
  danet::ReflectionVar<uint16_t> score{"score", &tickets, 2};
  danet::ReflectionVar<uint16_t> tickets{"tickets", &orderCooldownTotal, 3};
  danet::ReflectionVar<uint32_t> orderCooldownTotal{"orderCooldownTotal", &orderCooldownLeft, 4};
  danet::ReflectionVar<uint32_t> orderCooldownLeft{"orderCooldownLeft", &spawnScore, 5};
  danet::ReflectionVar<uint32_t> spawnScore{"spawnScore", &roundScore, 6};
  danet::ReflectionVar<float> roundScore{"roundScore", nullptr, 7};
  explicit TeamData(ParserState *state, mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : ReflectableObject(state, oid)  {
    varList.head = &score;
    varList.tail = &roundScore;
  }
  friend ParserState;
};

