// generated by replay parser codegen version 0.2
#pragma once

class UFXReflectable : public danet::ReflectableObject {
public:
  DECL_REFLECTION(UFXReflectable, danet::ReflectableObject)

  UFXReflectable() : ReflectableObject() { varList.head = &; }
};

ECS_DECLARE_CREATABLE_TYPE(UFXReflectable);
