// generated by replay parser codegen version 0.2
#pragma once

class UnitWeaponsMask : public danet::ReflectableObject {
public:
  DECL_REFLECTION(UnitWeaponsMask, danet::ReflectableObject)

  danet::ReflectionVar<danet::WeaponsMask> dummyVarForAmmoPartsMask{"dummyVarForAmmoPartsMask", nullptr, 2,
                                                                    danet::WeaponsCoder};

  UnitWeaponsMask() : ReflectableObject() {
    varList.head = &dummyVarForAmmoPartsMask;
    varList.tail = &dummyVarForAmmoPartsMask;
  }
};

ECS_DECLARE_CREATABLE_TYPE(UnitWeaponsMask);
