// generated by replay parser codegen version 0.2
#pragma once

class UnitWeaponsMask : public danet::ReflectableObject {
public:
  DECL_REFLECTION(UnitWeaponsMask, danet::ReflectableObject)
  void drawObject() const override;
  danet::ReflectionVar<danet::WeaponsMask> dummyVarForAmmoPartsMask{"dummyVarForAmmoPartsMask", nullptr, 2, danet::WeaponsCoder};
  explicit UnitWeaponsMask(mpi::ObjectID oid = mpi::INVALID_OBJECT_ID) : ReflectableObject(oid)  {
    varList.head = &dummyVarForAmmoPartsMask;
    varList.tail = &dummyVarForAmmoPartsMask;
  }
  friend ParserState;
};

ECS_DECLARE_CREATABLE_TYPE(UnitWeaponsMask);
