// generated by replay parser codegen version 0.2
#include "modules/mpi/codegen_objects.h"
#include "modules/mpi/types.h"
#include "mpi/codegen/ReflIncludes.h"
#include "modules/mpi/mpi.h"
PyCodegenObjects py_codegen_objects;
void PyCodegenObjects::include(py::module_ &m) {
  DO_INCLUDE()
  py_mpi_types.include(m);
  py_mpi.include(m);
  auto mpi = m.def_submodule("mpi");
  py::class_<MPlayer, danet::ReflectableObject, std::unique_ptr<MPlayer, py::nodelete>>(mpi, "MPlayer")
    .def_property_readonly("uid", [](MPlayer*ths){return &ths->uid.data;})
    .def_property_readonly("invitedNickName", [](MPlayer*ths){return &ths->invitedNickName.data;})
    .def_property_readonly("nickLocKey", [](MPlayer*ths){return &ths->nickLocKey.data;})
    .def_property_readonly("ClanTag", [](MPlayer*ths){return &ths->ClanTag.data;})
    .def_property_readonly("Title", [](MPlayer*ths){return &ths->Title.data;})
    .def_property_readonly("publicFlags", [](MPlayer*ths){return &ths->publicFlags.data;})
    .def_property_readonly("decals", [](MPlayer*ths){return &ths->decals.data;})
    .def_property_readonly("team", [](MPlayer*ths){return &ths->team.data;})
    .def_property_readonly("countryId", [](MPlayer*ths){return &ths->countryId.data;})
    .def_property_readonly("memberId", [](MPlayer*ths){return &ths->memberId.data;})
    .def_property_readonly("customState", [](MPlayer*ths){return &ths->customState.data;})
    .def_property_readonly("score", [](MPlayer*ths){return &ths->score.data;})
    .def_property_readonly("dummyForSupportPlanes", [](MPlayer*ths){return &ths->dummyForSupportPlanes.data;})
    .def_property_readonly("dummyForCrewUnitsList", [](MPlayer*ths){return &ths->dummyForCrewUnitsList.data;})
    .def_property_readonly("disabledByMatchingSlots", [](MPlayer*ths){return &ths->disabledByMatchingSlots.data;})
    .def_property_readonly("brokenSlots", [](MPlayer*ths){return &ths->brokenSlots.data;})
    .def_property_readonly("wasReadySlots", [](MPlayer*ths){return &ths->wasReadySlots.data;})
    .def_property_readonly("spareAircraftInSlots", [](MPlayer*ths){return &ths->spareAircraftInSlots.data;})
    .def_property_readonly("ownedSlots", [](MPlayer*ths){return &ths->ownedSlots.data;})
    .def_property_readonly("classinessMark", [](MPlayer*ths){return &ths->classinessMark.data;})
    .def_property_readonly("timeToRespawn", [](MPlayer*ths){return &ths->timeToRespawn.data;})
    .def_property_readonly("timeToRespawnInCoop", [](MPlayer*ths){return &ths->timeToRespawnInCoop.data;})
    .def_property_readonly("forcedRespawn", [](MPlayer*ths){return &ths->forcedRespawn.data;})
    .def_property_readonly("timeToKick", [](MPlayer*ths){return &ths->timeToKick.data;})
    .def_property_readonly("guiState", [](MPlayer*ths){return &ths->guiState.data;})
    .def_property_readonly("spectatedModelIndex", [](MPlayer*ths){return &ths->spectatedModelIndex.data;})
    .def_property_readonly("dummyForCountUsedSlots", [](MPlayer*ths){return &ths->dummyForCountUsedSlots.data;})
    .def_property_readonly("dummyForSpawnCosts", [](MPlayer*ths){return &ths->dummyForSpawnCosts.data;})
    .def_property_readonly("dummyForSpawnDelayTimes", [](MPlayer*ths){return &ths->dummyForSpawnDelayTimes.data;})
    .def_property_readonly("dummyForKillStreaksProgress", [](MPlayer*ths){return &ths->dummyForKillStreaksProgress.data;})
    .def_property_readonly("state", [](MPlayer*ths){return &ths->state.data;})
    .def_property_readonly("squadScore", [](MPlayer*ths){return &ths->squadScore.data;})
    .def_property_readonly("ownedUnitRef", [](MPlayer*ths){return &ths->ownedUnitRef.data;})
    .def_property_readonly("controlledUnitRef", [](MPlayer*ths){return &ths->controlledUnitRef.data;})
    .def_property_readonly("supportUnitRef", [](MPlayer*ths){return &ths->supportUnitRef.data;})
    .def_property_readonly("wreckedPartShipUnitRef", [](MPlayer*ths){return &ths->wreckedPartShipUnitRef.data;})
    .def_property_readonly("dummyForRoundScore", [](MPlayer*ths){return &ths->dummyForRoundScore.data;})
    .def_property_readonly("dummyForPlayerStat", [](MPlayer*ths){return &ths->dummyForPlayerStat.data;})
    .def_property_readonly("dummyForFootballStat", [](MPlayer*ths){return &ths->dummyForFootballStat.data;})
    .def_property_readonly("realNick", [](MPlayer*ths){return &ths->realNick.data;})
    .def_property_readonly("squadronId", [](MPlayer*ths){return &ths->squadronId.data;})
    .def_property_readonly("forceLockTarget", [](MPlayer*ths){return &ths->forceLockTarget.data;})
    .def_property_readonly("cachedIsAutoSquad", [](MPlayer*ths){return &ths->cachedIsAutoSquad.data;})
    .def_property_readonly("nickFrame", [](MPlayer*ths){return &ths->nickFrame.data;})
    .def_property_readonly("missionSupportUnitRef", [](MPlayer*ths){return &ths->missionSupportUnitRef.data;})
    .def_property_readonly("missionSupportUnitEnabled", [](MPlayer*ths){return &ths->missionSupportUnitEnabled.data;})
    .def_property_readonly("rageTokens", [](MPlayer*ths){return &ths->rageTokens.data;})
  ;
  py::class_<TeamData, danet::ReflectableObject, std::unique_ptr<TeamData, py::nodelete>>(mpi, "TeamData")
    .def_property_readonly("score", [](TeamData*ths){return &ths->score.data;})
    .def_property_readonly("tickets", [](TeamData*ths){return &ths->tickets.data;})
    .def_property_readonly("orderCooldownTotal", [](TeamData*ths){return &ths->orderCooldownTotal.data;})
    .def_property_readonly("orderCooldownLeft", [](TeamData*ths){return &ths->orderCooldownLeft.data;})
    .def_property_readonly("spawnScore", [](TeamData*ths){return &ths->spawnScore.data;})
    .def_property_readonly("roundScore", [](TeamData*ths){return &ths->roundScore.data;})
  ;
  py::class_<GlobalElo, danet::ReflectableObject, std::unique_ptr<GlobalElo, py::nodelete>>(mpi, "GlobalElo")
    .def_property_readonly("teamAvgEloRatings", [](GlobalElo*ths){return &ths->teamAvgEloRatings.data;})
  ;
  py::class_<GeneralState, danet::ReflectableObject, std::unique_ptr<GeneralState, py::nodelete>>(mpi, "GeneralState")
    .def_property_readonly("lastSuperArtilleryTime", [](GeneralState*ths){return &ths->lastSuperArtilleryTime.data;})
    .def_property_readonly("dummyForExitZonesSettings", [](GeneralState*ths){return &ths->dummyForExitZonesSettings.data;})
    .def_property_readonly("battleAreaChangeTime", [](GeneralState*ths){return &ths->battleAreaChangeTime.data;})
    .def_property_readonly("battleAreaChangeToId", [](GeneralState*ths){return &ths->battleAreaChangeToId.data;})
    .def_property_readonly("forcedMapCellsAir", [](GeneralState*ths){return &ths->forcedMapCellsAir.data;})
    .def_property_readonly("forcedMapCellsGround", [](GeneralState*ths){return &ths->forcedMapCellsGround.data;})
    .def_property_readonly("useCustomSuperArtillery", [](GeneralState*ths){return &ths->useCustomSuperArtillery.data;})
    .def_property_readonly("waterWindStrengthClamp", [](GeneralState*ths){return &ths->waterWindStrengthClamp.data;})
    .def_property_readonly("weatherEffectsDummyVar", [](GeneralState*ths){return &ths->weatherEffectsDummyVar.data;})
    .def_property_readonly("timeLeft", [](GeneralState*ths){return &ths->timeLeft.data;})
    .def_property_readonly("dummyForBombingEvent", [](GeneralState*ths){return &ths->dummyForBombingEvent.data;})
    .def_property_readonly("dummyForUnlimitedControlEvent", [](GeneralState*ths){return &ths->dummyForUnlimitedControlEvent.data;})
    .def_property_readonly("customState", [](GeneralState*ths){return &ths->customState.data;})
  ;
  py::class_<BaseZone, danet::ReplicatedObject, std::unique_ptr<BaseZone, py::nodelete>>(mpi, "BaseZone")
    .def_property_readonly("armyNo", [](BaseZone*ths){return &ths->armyNo.data;})
    .def_property_readonly("flags", [](BaseZone*ths){return &ths->flags.data;})
  ;
  py::class_<BombingZone, BaseZone, std::unique_ptr<BombingZone, py::nodelete>>(mpi, "BombingZone")
    .def_property_readonly("curZoneIntegrity", [](BombingZone*ths){return &ths->curZoneIntegrity.data;})
  ;
  py::class_<CaptureZone, BaseZone, std::unique_ptr<CaptureZone, py::nodelete>>(mpi, "CaptureZone")
    .def_property_readonly("mpTimeX100", [](CaptureZone*ths){return &ths->mpTimeX100.data;})
    .def_property_readonly("conqTeam", [](CaptureZone*ths){return &ths->conqTeam.data;})
    .def_property_readonly("iconIdx", [](CaptureZone*ths){return &ths->iconIdx.data;})
    .def_property_readonly("dummyVarForCapturers", [](CaptureZone*ths){return &ths->dummyVarForCapturers.data;})
    .def_property_readonly("dummyVarForCapturePart", [](CaptureZone*ths){return &ths->dummyVarForCapturePart.data;})
    .def_property_readonly("dummyVarForNumOfActiveCapturers", [](CaptureZone*ths){return &ths->dummyVarForNumOfActiveCapturers.data;})
  ;
  py::class_<RearmZone, BaseZone, std::unique_ptr<RearmZone, py::nodelete>>(mpi, "RearmZone")
  ;
  py::class_<ExitZone, BaseZone, std::unique_ptr<ExitZone, py::nodelete>>(mpi, "ExitZone")
  ;
  py::class_<PickupZone, BaseZone, std::unique_ptr<PickupZone, py::nodelete>>(mpi, "PickupZone")
    .def_property_readonly("showOnTacticalMap", [](PickupZone*ths){return &ths->showOnTacticalMap.data;})
  ;
}