// generated by replay parser codegen version 0.2
#include "modules/mpi/mpi.h"
#include "modules/mpi/codegen_types.h"
#include "modules/bind_readonly_vector.h"
#include "mpi/reflection.h"
#include "mpi/types.h"
#include "modules/mpi/bind_array.h"
#include "pybind11/stl_bind.h"
PyCodegenTypes py_codegen_types{};
void include_types_0(py::module &m);
void PyCodegenTypes::include(py::module_ &m) {
  DO_INCLUDE()
  py_mpi.include(m);
  auto mpi = m.def_submodule("mpi");
  auto gen = mpi.def_submodule("gen");
  py::class_<danet::RoundScore>(mpi, "RoundScore")
    .def_readonly("combined", &danet::RoundScore::combined)
    .def_readonly("scores", &danet::RoundScore::scores);
  py::class_<danet::dummyForFootballStat>(mpi, "dummyForFootballStat")
    .def_readonly("v1", &danet::dummyForFootballStat::v1)
    .def_readonly("v2", &danet::dummyForFootballStat::v2)
    .def_readonly("v3", &danet::dummyForFootballStat::v3);
  py::class_<danet::Crew>(mpi, "Crew")
    .def_readonly("e1", &danet::Crew::e1)
    .def_readonly("e2", &danet::Crew::e2)
    .def_readonly("v1", &danet::Crew::v1)
    .def_readonly("v2", &danet::Crew::v2);
  py::class_<danet::CrewUnitsList>(mpi, "CrewUnitsList").def_readonly("crew", &danet::CrewUnitsList::crew);
  py::class_<danet::dummyForPlayerStat>(mpi, "dummyForPlayerStat")
    .def_readonly("v1", &danet::dummyForPlayerStat::v1)
    .def_readonly("v2", &danet::dummyForPlayerStat::v2)
    .def_readonly("v3", &danet::dummyForPlayerStat::v3)
    .def_readonly("v4", &danet::dummyForPlayerStat::v4)
    .def_readonly("v5", &danet::dummyForPlayerStat::v5)
    .def_readonly("v6", &danet::dummyForPlayerStat::v6)
    .def_readonly("v7", &danet::dummyForPlayerStat::v7)
    .def_readonly("v8", &danet::dummyForPlayerStat::v8)
    .def_readonly("v9", &danet::dummyForPlayerStat::v9)
    .def_readonly("v10", &danet::dummyForPlayerStat::v10)
    .def_readonly("v11", &danet::dummyForPlayerStat::v11)
    .def_readonly("v12", &danet::dummyForPlayerStat::v12)
    .def_readonly("v13", &danet::dummyForPlayerStat::v13)
    .def_readonly("v14", &danet::dummyForPlayerStat::v14)
    .def_readonly("v15", &danet::dummyForPlayerStat::v15)
    .def_readonly("v16", &danet::dummyForPlayerStat::v16)
    .def_readonly("v17", &danet::dummyForPlayerStat::v17)
    .def_readonly("v18", &danet::dummyForPlayerStat::v18)
    .def_readonly("v19", &danet::dummyForPlayerStat::v19)
    .def_readonly("v20", &danet::dummyForPlayerStat::v20)
    .def_readonly("v21", &danet::dummyForPlayerStat::v21)
    .def_readonly("v22", &danet::dummyForPlayerStat::v22)
    .def_readonly("v23", &danet::dummyForPlayerStat::v23)
    .def_readonly("v24", &danet::dummyForPlayerStat::v24);
  py::class_<danet::streak>(mpi, "streak")
    .def_readonly("v1", &danet::streak::v1)
    .def_readonly("v2", &danet::streak::v2)
    .def_readonly("v3", &danet::streak::v3);
  py::class_<danet::dummyForKillStreaksProgress>(mpi, "dummyForKillStreaksProgress")
    .def_readonly("vals", &danet::dummyForKillStreaksProgress::vals);
  py::class_<danet::teamAvgEloRatings>(mpi, "teamAvgEloRatings").def_readonly("data", &danet::teamAvgEloRatings::data);
  py::class_<danet::zigZagPair>(mpi, "zigZagPair")
    .def_readonly("v1", &danet::zigZagPair::v1)
    .def_readonly("v2", &danet::zigZagPair::v2);
  py::class_<danet::dummyForExitZonesSettings>(mpi, "dummyForExitZonesSettings")
    .def_readonly("vals", &danet::dummyForExitZonesSettings::vals);
  py::class_<danet::WeatherEffect>(mpi, "WeatherEffect")
    .def_readonly("name", &danet::WeatherEffect::name)
    .def_readonly("effect_data", &danet::WeatherEffect::effect_data);
  py::class_<danet::WeatherEffects>(mpi, "WeatherEffects").def_readonly("effects", &danet::WeatherEffects::effects);
  py::class_<danet::UnitIdStruct>(mpi, "UnitIdStruct")
    .def_readonly("uid", &danet::UnitIdStruct::uid)
    .def_readonly("thang", &danet::UnitIdStruct::thang);
  py::class_<danet::dummyForDeathInfo>(mpi, "dummyForDeathInfo")
    .def_readonly("v1", &danet::dummyForDeathInfo::v1)
    .def_readonly("v2", &danet::dummyForDeathInfo::v2)
    .def_readonly("v3", &danet::dummyForDeathInfo::v3)
    .def_readonly("v4", &danet::dummyForDeathInfo::v4)
    .def_readonly("v5", &danet::dummyForDeathInfo::v5);
  py::class_<danet::KillerStruct>(mpi, "KillerStruct")
    .def_readonly("player_id", &danet::KillerStruct::player_id)
    .def_readonly("uid", &danet::KillerStruct::uid)
    .def_readonly("vehicle", &danet::KillerStruct::vehicle);
  py::class_<danet::DamagedState>(mpi, "DamagedState")
    .def_readonly("v1", &danet::DamagedState::v1)
    .def_readonly("v2", &danet::DamagedState::v2);
  bind_readonly_vector<std::vector<uint32_t>>(gen, "std_vector_uint32_t_");

  bind_readonly_vector<std::vector<danet::Crew>>(gen, "std_vector_danet_Crew_");

  bind_readonly_vector<std::vector<danet::streak>>(gen, "std_vector_danet_streak_");

  bind_array<float, 3>(mpi, "std_array_float_3_");

  bind_readonly_vector<std::vector<danet::zigZagPair>>(gen, "std_vector_danet_zigZagPair_");

  bind_readonly_vector<std::vector<danet::WeatherEffect>>(gen, "std_vector_danet_WeatherEffect_");

  bind_array<ecs::EntityId, 20>(mpi, "std_array_ecs_EntityId_20_");

  bind_readonly_vector<std::vector<uint8_t>>(gen, "std_vector_uint8_t_");

  bind_readonly_vector<std::vector<uint16_t>>(gen, "std_vector_uint16_t_");

  bind_readonly_vector<std::vector<danet::UnitId>>(gen, "std_vector_danet_UnitId_");

  bind_readonly_vector<std::vector<danet::UnitIdStruct>>(gen, "std_vector_danet_UnitIdStruct_");

  bind_array<std::string, 2>(mpi, "std_array_std_string_2_");

  bind_readonly_vector<std::vector<danet::DamagedState>>(gen, "std_vector_danet_DamagedState_");

  include_types_0(gen);
}
